export const ACTIVATE_FILTER = 'ACTIVATE_FILTER';
export const DEACTIVATE_FILTER = 'DEACTIVATE_FILTER';

export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_RATING = 'SORT_BY_RATING';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';
